In [3]:
import numpy as np

In [4]:
class Network(object):
    
    def __init__(self,sizes):
        self.num_layers = len(sizes)
        self.biases = [np.random.randn(y,1) for y in sizes[1:]] #trandn(x,y) x,y matrix with noraml standard distr
        self.weights = [np.random.randn(y,x) for x,y in zip(sizes[:-1],sizes[1:])]

In [5]:
net = Network([2,3,1]) # I, H, O

In [6]:
sizes = [2,3,1]
sizes[1:]

[3, 1]

In [7]:
test = [np.random.randn(y,1) for y in sizes[1:]]

In [8]:
test # total 4 biases, 3 for I to H and 1 for H to O, each bias for one out

[array([[-0.33962214],
        [-0.38833968],
        [-1.89967585]]), array([[-0.48694227]])]

In [23]:
sizes[:-1]

[2, 3]

In [24]:
[(y,x) for x,y in zip(sizes[:-1],sizes[1:])]

[(3, 2), (1, 3)]

In [18]:
weights = [np.random.randn(y,x) for x,y in zip(sizes[:-1],sizes[1:])]

In [19]:
weights # 2x3 from I to H, 3 x 1 from H to O

[array([[-0.30426818,  0.46165773],
        [-1.14896913,  0.05557586],
        [ 0.36281306,  1.2813611 ]]),
 array([[-0.43470388,  0.16982938,  0.04471445]])]

In [25]:
def sigmoid(z):
    return 1.0/(1.0+np.exp(-z))

In [ ]:
def feedforward(self,a):
    for b,w in zip(self.biases,self.weights):
        a=sigmoid(np.dot(w,a)+b) # not element wise; still vectorized
    return a

In [27]:
[(b,w) for b,w in zip(net.biases,net.weights)]

[(array([[-0.70737831],
         [ 0.47151407],
         [ 1.21203804]]), array([[-1.13917229, -0.16980475],
         [ 0.98844458, -0.77894872],
         [-1.51859318,  1.52514413]])),
 (array([[ 1.19407097]]), array([[ 0.15218273,  1.77546301, -1.20578639]]))]

In [29]:
x = np.array([[1],[2],[3]])
y = np.array([[4,5],[6,7],[8,9]])

In [30]:
[(a,b) for a,b in zip(x,y)]

[(array([1]), array([4, 5])),
 (array([2]), array([6, 7])),
 (array([3]), array([8, 9]))]

In [32]:
def SGD(self,training_data,epochs,mini_batch_size,eta,test_data=None):
    if test_data:
        n_test = len(test_data)
    n= len(training_data)
    for j in xrange(epochs):
        random.shuffle(training_data)
        mini_batches = [training_data[k:k+mini_batch_size]
                        for k in xrange(0,n,mini_batch_size)]
        for mini_batch in mini_batches:
            self.update_mini_batch(mini_batch,eta)
        if test_data:
            print("Epoch {0}: {1}/{2}".format(j,self.evaluate(test_data),n_test))
        else:
            print("Epoch {0} complete".format(j))

In [34]:
def update_mini_batch(self,mini_batch,eta):
    nable_b = [np.zeros(b.shape) for b in self.biases]
    nabla_w = [np.zeros(w.shape) for w in self.weights]
    for x,y in mini_batch:
        delta_nabla_b,delta_nabla_w = self.backprop(x,y)
        nabla_b = [nb+dnb for nb,dnb in zip(nabla_b,delta_nabla_b)]
        nabla_w = [nw+dnw for nw,dnw in zip(nabla_w,delta_nabla_w)]
    self.weights = [w-(eta/len(mini_batch))*nw
                   for w,nw in zip(self.weights,nw)] 
    self.biases = [b-(eta/len(mini_batch))*nb
                   for b,nb in zip(self.biases,nabla_b)]